# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_comment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_follow',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='forum.Profile'),
        ),
        migrations.AlterField(
            model_name='p_follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='forum.Profile'),
        ),
    ]
