# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170713_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ppic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
