# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_ppic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppic',
            name='file',
        ),
        migrations.AddField(
            model_name='ppic',
            name='ppic',
            field=models.ImageField(default='~/AMA/ama/pictures/default.jpg', upload_to='~/AMA/ama/pictures/'),
        ),
    ]
