# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Topic', '0001_initial'),
        ('Question', '0004_q_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Related_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question.Question')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Topic.Topic')),
            ],
        ),
    ]
