# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Topic', '0002_auto_20170708_1719'),
        ('Question', '0005_related_topic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='q_follow',
            unique_together=set([('follower', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='q_upvote',
            unique_together=set([('upvoter', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='related_topic',
            unique_together=set([('topic', 'question')]),
        ),
    ]
