# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Answer', '0002_a_upvote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='a_upvote',
            unique_together=set([('upvoter', 'answer')]),
        ),
    ]
