# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0006_auto_20170708_1719'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Answer', '0003_auto_20170708_1719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('author', 'question')]),
        ),
    ]
